#!/usr/bin/env python
import math
import os
import sys

todo_file = os.path.join(os.environ['TODO_DIR'], 'todo.txt')
with open(todo_file) as f:
    lines = f.readlines()

try:
    line_num = int(sys.argv[2])
    line_num = int(math.copysign(1, line_num) * (abs(line_num) - 1))
except IndexError:
    line_num = len(lines) - 1

if line_num > 0:
    lines.insert(0, lines.pop(line_num))
else:
    lines.append(lines.pop(-line_num))

with open(todo_file, 'w') as f:
    f.writelines(lines)

